## Degree centrality

```{r}

data <- toVisNetworkData(g)

# Create numerical vector of various centrality measures --  betweenness, eignecentrality, and pagerank.

data$nodes$value <- as.numeric(centralization.degree(g)$res/length(E(g)))
data$nodes$title <- data$nodes$label
data$nodes$label <- NULL

visNetwork(nodes = data$nodes, edges = data$edges) %>% 
  visIgraphLayout(randomSeed = 123) %>%
  visNodes(scaling = list(min = 30, max = 100), color = list(background = "lightblue", highlight = "yellow")) %>%
  visEdges(color = list(color = "cornflowerblue", highlight = "red"))

```


## Betweenness centrality
```{r}
data <- toVisNetworkData(g)

# Create numerical vector of various centrality measures --  betweenness, eignecentrality, and pagerank.

data$nodes$value <- as.numeric(betweenness(g))
data$nodes$title <- data$nodes$label
#data$nodes$label <- NULL

visNetwork(nodes = data$nodes, edges = data$edges) %>% 
  visIgraphLayout(randomSeed = 123) %>%
  visNodes(scaling = list(min = 30, max = 100), color = list(background = "lightblue", highlight = "yellow")) %>%
  visEdges(color = list(color = "cornflowerblue", highlight = "red"))
```


## Eigenvector centrality
```{r}
data <- toVisNetworkData(g)

# Create numerical vector of various centrality measures --  betweenness, eignecentrality, and pagerank.

data$nodes$value <- as.numeric(eigen_centrality(g)$vector)
data$nodes$title <- data$nodes$label
data$nodes$label <- NULL

visNetwork(nodes = data$nodes, edges = data$edges) %>% 
  visIgraphLayout(randomSeed = 123) %>%
  visNodes(scaling = list(min = 30, max = 100), color = list(background = "lightblue", highlight = "yellow")) %>%
  visEdges(color = list(color = "cornflowerblue", highlight = "red"))
```
